---

- name: Clean previous runs of k3s-init
  systemd:
    name: k3s-init
    state: stopped
  failed_when: false

- name: Clean previous runs of k3s-init
  command: systemctl reset-failed k3s-init
  failed_when: false
  changed_when: false
  args:
    warn: false  # The ansible systemd module does not support reset-failed

- name: Deploy vip manifest
  include_tasks: vip.yml
  when: vars['kube_vip_configure'] 

- name: Deploy gVisor CRI runtime manifest
  include_tasks: gvisor.yml
  when: vars['k3s_gvisor_install'] 

- name: Deploy calico CNI
  include_tasks: calico.yml
  when: vars['cni_calico'] 

- name: Deploy metallb manifest
  include_tasks: metallb.yml

- name: Init cluster master 0 first transient k3s-init service
  command:
    cmd: "systemd-run -p RestartSec=2 \
                      -p Restart=on-failure \
                      --unit=k3s-init \
                      k3s server --cluster-init \
                      {{ extra_server_args | default('') }}"
    creates: "{{ systemd_dir }}/k3s.service"
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: Wait for node-token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: Register node-token file access mode
  stat:
    path: /var/lib/rancher/k3s/server
  register: p
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: Change file access node-token
  file:
    path: /var/lib/rancher/k3s/server
    mode: "g+rx,o+rx"
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: Read node-token from master
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: Store Master node-token
  set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: Restore node-token file access
  file:
    path: /var/lib/rancher/k3s/server
    mode: "{{ p.stat.mode }}"
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: Init cluster other masters other than 0 transient k3s-init service
  command:
    cmd: "systemd-run -p RestartSec=2 \
                      -p Restart=on-failure \
                      --unit=k3s-init \
                      k3s server --server https://{{ hostvars[groups['master'][0]].k3s_node_ip | split(',') | first | ansible.utils.ipwrap }}:6443 \
                      --token {{ hostvars[groups['master'][0]].token }} \
                      {{ extra_server_args | default('') }}"
    creates: "{{ systemd_dir }}/k3s.service"
  when:
    - ansible_hostname != hostvars[groups['master'][0]]['ansible_hostname']
    - groups['master'] | length > 1

- name: Verification
  block:
    - name: Verify that all nodes actually joined (check k3s-init.service if this fails)
      command:
        cmd: k3s kubectl get nodes -l "node-role.kubernetes.io/master=true" -o=jsonpath="{.items[*].metadata.name}"
      register: nodes
      until: nodes.rc == 0 and (nodes.stdout.split() | length) == (groups['master'] | length)
      retries: "{{ retry_count | default(40) }}"
      delay: 10
      changed_when: false
  always:
    - name: Save logs of k3s-init.service
      include_tasks: fetch_k3s_init_logs.yml
      when: log_destination
      vars:
        log_destination: >-
          {{ lookup('ansible.builtin.env', 'ANSIBLE_K3S_LOG_DIR', default=False) }}
    - name: Kill the temporary service used for initialization
      systemd:
        name: k3s-init
        state: stopped
      failed_when: false
  when: not ansible_check_mode

- name: Copy K3s service file
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes


- name: Create directory .kube
  file:
    path: "{{ ansible_user_dir }}/.kube"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: "u=rwx,g=rx,o="

- name: Copy config file to user home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ ansible_user_dir }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user_id }}"
    mode: "u=rw,g=,o="

- name: Configure kubectl cluster to {{ endpoint_url }}
  command: >-
    k3s kubectl config set-cluster default
      --server={{ endpoint_url }}
      --kubeconfig {{ ansible_user_dir }}/.kube/config
  changed_when: true
  vars:
    endpoint_url: >-
      https://{{ apiserver_endpoint | ansible.utils.ipwrap }}:6443
  # Deactivated linter rules:
  #   - jinja[invalid]: As of version 6.6.0, ansible-lint complains that the input to ipwrap
  #                     would be undefined. This will not be the case during playbook execution.
  # noqa jinja[invalid]

- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link
